(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  Script generated:  2017-01-12 16:23:08
  From session:  rapid3
  Captured on:  2017-01-12 14:26:06
  From server:  testplants-Mac-2
* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)

Image at "MyPortfolio"
Image at "MyPortfolio_0001"
Image at "MyPortfolio_0002"
Image at "MyPortfolio_0003"
Image at "Next"
Image at "Help"
Image at "image0120"
Image at "SearchWeb"
