(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  Script generated:  2017-01-11 13:28:18
  From session:  untitled session
  Captured on:  2017-01-11 13:27:16
  From server:  testplants-Mac-2
* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)

Click "Chess"
Click "image0008"
Click "QuickTimePlayer"
DoubleClick "image0009"
Click "image0010"
Click "image0011"
Click "image0012"
Click "image0013"
Click "image0014"
