(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  Script generated:  2017-02-10 12:50:52
  From session:  untitled session
  Captured on:  2017-02-02 21:37:33
  From server:  testplants-Mac-2
* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)

Click "image0080"
Click "image0001"
Click "image0002"
Click "ilLI"
Click "image0003"
Click "image0004"
Click "image0005"
Click "image0006"
