(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  Script generated:  2017-02-13 15:17:16
  From session:  untitled session
  Captured on:  2017-02-13 15:16:37
  From server:  testplants-Mac-2
* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)
Click "image0056"

Click "mSafari_0001"
Click "AboutSafari"
Click "image0052"
Click "FileEditViewHistoryBookmarksWi_0004"
Click "Find"
Click "image0053"
Click "image0054"
