(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  Script generated:  2017-01-17 13:51:51
  From session:  untitled session
  Captured on:  2017-01-17 13:50:51
  From server:  testplants-Mac-2
* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)

Click "Edit"
Click "image0057"
DoubleClick "image0058"
DoubleClick "image0059"
Click "UntitledQ"
Drag "image0060"
Drop "image0061"
Click "eggplantFileEdit"
Click "QuiteggPlant"
