(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  Script generated:  2017-01-18 10:02:00
  From session:  untitled session
  Captured on:  2017-01-17 14:59:01
  From server:  testplants-Mac-2
* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)

Click (Image:"UFinder", WaitFor:2)
Click (Image:"UFinder_0001", WaitFor:3)
Click (Image:"AboutFinder", WaitFor:4)
Click (Image:"AboutFinder_0001", WaitFor:6)
