(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  Script generated:  2017-01-19 16:45:16
  From session:  untitled session
  Captured on:  2017-01-19 16:42:52
  From server:  testplants-Mac-2
* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)

Click "image0108"
Click "image0109"
Drag "image0110"
Drop "image0111"
Click "image0112"
Click "image0113"
Click "image0114"
Click "image0115"
