(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  Script generated:  2017-01-30 13:26:44
  From session:  untitled session
  Captured on:  2017-01-30 13:25:54
  From server:  testplants-Mac-2
* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)

DoubleClick "image0447"
Click "image0448"
DoubleClick "image0449"
Click "image0450"
Click "image0451"
Click "image0452"
Click "Cance"
