(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  Script generated:  2017-01-18 10:33:59
  From session:  untitled session
  Captured on:  2017-01-18 10:33:41
  From server:  testplants-Mac-2
* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)

Drag "image0186"
Drop "789789651_0001"
Drag "image0187"
Drop "image0188"
Click "image0189"
Click "image0190"
Click "image0191"
Click "image0192"
Click "image0193"
Click "image0194"
Click "image0195"
