(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  Script generated:  2017-01-19 15:06:24
  From session:  untitled session
  Captured on:  2017-01-19 14:56:23
  From server:  testplants-Mac-2
* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)

Click "image0092"
Click "image0093"
Click "image0094"
Click "iPad"
Click "nnnnIS"
Click "Music"
Click "Support"
Click "image0095"
