(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  Script generated:  2017-01-20 09:56:02
  From session:  untitled session
  Captured on:  2017-01-19 15:24:46
  From server:  testplants-Mac-2
* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)

RightClick "image0099"
Click "image0100"
Drag "image0126"
Drop "image0127"
Click "image0131"
Click "image0132"
Click "Chess"
Click "image0133"
Click "image0138"
Click "image0139"
Click "image0142"
Click "image0143"
