(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  Script generated:  2017-01-26 09:20:53
  From session:  untitled session
  Captured on:  2017-01-26 09:20:31
  From server:  testplants-Mac-2
* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)

Click "image0412"
Click "image0413"
Click "image0414"
Click "image0415"
Click "image0416"
Click "image0417"
Click "image0418"
Click "image0419"
