(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  Script generated:  2017-01-12 11:40:56
  From session:  SutRapidcapture
  Captured on:  2017-01-12 11:39:26
  From server:  testplants-Mac-2
* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)

Click "image0015"
Click "image0016"
Click "image0017"
Click "image0018"
Drag "image0019"
Drop "image0020"
Drag "image0021"
Drop "image0022"
Click "image0023"
