apple"parent"

Untitled
clerk "NewhelperNov29.suite/Scripts/Untitled"
clerk "/Users/mickeykuni/Documents/NewhelperNov29.suite/Scripts/Untitled"

clerk "Nov29"
clerk "clerk"

Folder1.NewFolder.Untitled
clerk "Folder1/NewFolder/trap"
Nov29
trap "Untitled"
trap "/Users/mickeykuni/Documents/NewhelperNov29.suite/Scripts/"
reena
trap "/Users/reenakuni/Documents/NewhelperNov29.suite/Scripts/Untitled"
trap "NewhelperNov29.suite/Scripts/Untitled"
