apple"parent"

Untitled
Manager "NewhelperNov29.suite/Scripts/Untitled"
Manager "/Users/mickeykuni/Documents/NewhelperNov29.suite/Scripts/Untitled"

Manager "Nov29"
Manager "Manager"

Folder1.NewFolder.Untitled
Manager "Folder1/NewFolder/trap"
Nov29
trap "Untitled"
trap "/Users/mickeykuni/Documents/NewhelperNov29.suite/Scripts/"
reena
trap "/Users/reenakuni/Documents/NewhelperNov29.suite/Scripts/Untitled"
trap "NewhelperNov29.suite/Scripts/Untitled"
