(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  Script generated:  2017-02-16 13:34:52
  From session:  untitled session
  Captured on:  2017-02-16 13:34:19
  From enter:  testplants-Mac-2
* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)

Click "image0018"
Click "image0019"
Click "image0020"
Click "image0021"
Click "image0022"
Click "image0023"
Click "image0024"
Click "image0025"
Click "image0026"
Click "image0027"
