(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  Script generated:  2017-02-16 15:27:21
  From session:  untitled session
  Captured on:  2017-02-16 15:26:41
  From enter:  testplants-Mac-2
* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)

Click "hithere/image0001"
Click "hithere/image0002"
Click "hithere/image0003"
Click "hithere/image0004"
Click "hithere/image0005"
