(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  Script generated:  2017-02-14 11:11:38
  From session:  untitled session
  Captured on:  2017-02-14 11:10:17
  From server:  testplants-Mac-2
* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)

Click "hello/image0001"
Click "hello/image0001"
Click "hello/image0001"
Click "hello/CioriTvt"
Click "hello/image0001"
Click "hello/Cance"

dfdlkfkldlkgflk  reena 