(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  Script generated:  2017-02-10 15:00:22
  From session:  untitled session
  Captured on:  2017-02-10 14:58:50
  From server:  testplants-Mac-2
* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)

Click "image0035"
Click "image0036"
Click "image0037"
Click "image0038"
Click "image0039"
Click "image0040"
Click "NewScript_0001"
Click "lan"
click "Chess"
Click "IChess/IChess_new"
